name: NoticeBarrel
version: '${version}'
main: com.noticemc.noticebarrel.NoticeBarrel
api-version: 1.17
softdepend:
  - GriefPrevention
  - QuickShop
permissions:
  NoticeBarrel.*:
    description: "Allows the user to use NoticeBarrel."
    default: op
  NoticeBarrel.admin:
    description: "Allows the user to use NoticeBarrel outside of yourself claim."
    default: op
  NoticeBarrel.changeBarrel:
    description: "Allows the user to change the barrel."
    default: false
  NoticeBarrel.reload:
    description: "Allows the user to reload the plugin."
    default: op
